version: '3.7'

services:
  nginx:
    build:
      context: nginx
    depends_on:
      - wp
      - api
      - client
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 20080:80
    networks:
      - app-network

  #certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw
  #    - ./certbot/conf/:/etc/letsencrypt/:rw
  #  #certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d example.org
  #  #certbot certonly --webroot --webroot-path /var/www/certbot/ -d dev.vechorka.ru

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-db}
      - MYSQL_USER=${DB_USER:-db_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp:
    image: wordpress
    container_name: wp
    restart: always
    volumes:
      - ./admin.wp/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./admin.wp/wordpress:/var/www/html
      - ./admin.wp/wordpress/wp-config.php:/var/www/html/wp-config.php
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST:-db}
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-0}
    depends_on:
      - db
    networks:
      - app-network

  api:
    build:
      context: api.nest
      target: production
    container_name: api-nest
    depends_on:
      - db
    env_file:
      - .env
    #environment:
    #  - DB_HOST=${DB_HOST:-db}
    restart: always
    ports:
      - 10000:10000
    #command: npm run start:dev
    networks:
      - app-network

  client:
    build:
      context: client.next
      dockerfile: ./Dockerfile
    container_name: client-next
    depends_on:
      - api
      - wp
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
